#+STARTUP: indent align hidestars
#+TITLE: org-publish Tips & Tricks
#+DESCRIPTION: Tips & Tricks for making your life easier when publishing blogs with emacs on minimum steroids.
#+HTML_HEAD: <meta property="og:title" content="org-publish Tips & Tricks" />
#+HTML_HEAD: <meta property="og:description" content="Tips & Tricks for making your life easier when publishing blogs with emacs on minimum steroids." />
#+HTML_HEAD: <meta property="og:type" content="website" />
#+MACRO: a @@html:<a href='$2' rel='external nofollow'>$1</a>@@

* Setting up the environment
:PROPERTIES:
:ID:       a915e191-9545-4b97-a2fe-a3f5c2cb21ea
:PUBDATE:  <2020-03-01 dom. 23:47>
:END:
- https://orgmode.org/manual/In_002dbuffer-Settings.html
- https://orgmode.org/manual/Publishing-links.html#Publishing-links
- Customize the variable org-id-link-to-org-use-id and set it to t (AKA Create ID to make link)

#+begin_src elisp
(add-to-list 'package-archives
    '("org" . "https://orgmode.org/elpa/") t)
(add-to-list 'package-archives
    '("org-plus-contrib" . "https://orgmode.org/elpa/") t)

(unless (package-installed-p 'org-plus-contrib)
  (package-refresh-contents)
  (package-install 'org-plus-contrib))
(require 'org-plus-contrib)
#+end_src

* TODO Template Publicación
:PROPERTIES:
:ID:       ce948347-c8bd-42c2-8baf-06e236b31d6e
:PUBDATE:  <2020-03-01 dom. 23:47>
:END:

- Un directorio por <<TEMA>>
- Cada headline con un identificador [[file:foo.org::#custom-id]]
- Con deft https://jblevins.org/projects/deft/ buscar dentro de las carpeta del proyecto los temas asociados y copiar el ID
  - Copiar el link con org-id-copy

* AAAA
:PROPERTIES:
:ID:       81e82f6e-edd1-416e-b5f2-0f19b7902f11
:PUBDATE:  <2020-03-01 dom. 23:47>
:END:
** Initial Problem
:PROPERTIES:
:ID:       bb947b4f-2ad0-400e-88ea-1fd3f2aecb73
:END:
The elements wrapping the headline content were not contained inside a parent div/section, making it pretty hard to organize the content in the page since they kept overlapping each other using grid and flexbox was impossible due to them not having a parent html element.
The TOC needed to grow in size in relation to the content of the page. The logical solution would be to use flexbox but since we already discarded that as an option I wah stuck with traditional "box" manipulation or css grid.

#+BEGIN_EXAMPLE
+-------+--------------+
|       |    header    |
|       +--------------+
|       |  headline-1  |
|  toc  |  headline-2  |
|       |     ....     |
|       |              |
|       |  headline-N  |
+-------+--------------+
|        footer        |
+----------------------+
#+END_EXAMPLE

** The Solution
:PROPERTIES:
:ID:       cff91b8d-7bba-4f39-ad17-88a6c0ad4f41
:END:
The template needs to have three rows and two columns but the content at [1][1] is forced into position so we don't need to reference it by name. 

#+BEGIN_SRC css
#content {
    display: inline-grid;
    grid-template-areas: 'toc header'
        'toc _'
        'toc footer';
}
#+END_SRC

The header is positioned using the grid-area name

#+BEGIN_SRC css
header {
    grid-area: header;
    width: auto;
} /* document title */
#+END_SRC

The content within the headlines in the org file has to be forced into position with the =grid-column= attribute and since the amount of headlines that each page has is variable we need to use the grid-row attribute and set it to "auto".

#+BEGIN_SRC css
[class^="outline-"] {
    grid-row: auto;
    grid-column: 2;
}
#+END_SRC

The TOC can be positioned in the traditional way but the bottom of it should reach the footer section which can be done by manipulating the grid-row-end attribut and setting it to an absurdly high number.

#+BEGIN_SRC css
#table-of-contents {
    grid-area: toc;
    grid-row-end: 999;
}
#+END_SRC

The syntax highlighting capabilities are available once you install the htmlize package. [[https://stackoverflow.com/a/24087061][Link to StackOverflow answer]]. 

#+BEGIN_SRC elisp
(use-package htmlize
  :init
  :ensure t)
#+END_SRC

* SEO Improvements
:PROPERTIES:
:ID:       5090516a-6bf7-4dfd-b60e-3f81b4ac712b
:PUBDATE:  <2020-03-01 dom. 23:47>
:END:
** Capturing links
:PROPERTIES:
:ID:       837f22ed-efed-43db-bb24-d5f10d5b6f7c
:END:
Linking to a website or piece of content would normally increase that website’s domain authority. But with a nofollow tag, it won’t.

Unfortunately using the #+ATTR_HTML tag would wrap the hyperlink in a <p> element, as it's described in {{{a(this old reddit thread,https://www.reddit.com/r/emacsorg/comments/5afnjy/emacs_org_html_export_attr_html_for_inline_tags/)}}} however in the org manual I found out that you can {{{a(quote HTML tags,https://orgmode.org/org.html#Quoting-HTML-tags)}}}

Once we set up a way for {{{a(capturing our templates in place,https://emacs.stackexchange.com/a/30598)}}} the next way is to set up the template using the inline html trick and {{{a(template expansion,https://orgmode.org/manual/Template-expansion.html#Template-expansion)}}} alongside {{{a(macro replacement,https://orgmode.org/manual/Macro-Replacement.html)}}}.
#+begin_src elisp
;; marcos are pre-processed... dah!
#+MACRO: a @@html:<a href='$2' rel='external nofollow'>$1</a>@@

(defun org-capture-at-point ()
  "Insert an org capture template at point."
  (interactive)
  (org-capture 0))

(global-set-key (kbd "C-c c") #'org-capture-at-point)

(setq org-capture-templates
      '(("l" "Link nofollow" plain (file "") "{{{a(%?,%x)}}}")))
#+end_src

Another crucial part is to set up the Open Graph Tags so your content gets shared in a beautiful way in social media.

#+begin_src elisp
#+HTML_HEAD: <meta property="og:title" content="Title" />
#+HTML_HEAD: <meta property="og:description" content="My Site Description" />
#+HTML_HEAD: <meta property="og:type" content="website" />
#+end_src

{{{a(https://www.google.com, nah no te la puedo)}}}
